# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CgPanda.com
email: do_not_tell_you@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am an experienced Game Developer, but a newbie Web Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: do_not_tell_you_:)
github_username:  lai3d

# Build settings
markdown: kramdown
